### ISSUE TITLE
Write PHP module which makes use of RNP functionality.

### ISSUE THREAD

**Issue by ni4** [rnpgp/php-rnp#1]
## Description

It appears that there are not much of OpenPGP implementations, available for the PHP language. Given that Drupal and Wordpress are quite popular as a site backend there could be some demand for PHP PGP module. Hopefully somebody from the PHP world would give us sime insights on this so we may prioritize this issue.

**Comment by ronaldtse** [comment]
@antonsviridenko I wonder if there's an automatic way of publishing the PECL package?

I've set the following secrets in the repo:
* `RNP_PECL_USERNAME`
* `RNP_PECL_PASSWORD`

However I've not found a way to upload a package without the browser...

**Comment by ronaldtse** [comment]
@antonsviridenko if you can upload the output of `pear package` here I can upload it directly to PECL.

**Comment by antonsviridenko** [comment]
@ronaldtse here it is https://github.com/rnpgp/php-rnp/releases/download/v0.1/rnp-0.1.tgz

sha256sum rnp-0.1.tgz 
```
e7f2e13c69a39b0576c86d5460910ee4c98b88d3993ee7e9c49bfade686d2fea  rnp-0.1.tgz
```

**Comment by ronaldtse** [comment]
Error, can you ping me when there's an update? Thanks!
<img width="880" alt="Screen Shot 2022-10-25 at 5 59 25 PM" src="https://user-images.githubusercontent.com/11865/197744162-94a3c92f-d8a6-4e5a-9893-9fee7edfa561.png">

**Comment by antonsviridenko** [comment]
@ronaldtse 
ok, updated version to 0.1.1
https://github.com/rnpgp/php-rnp/releases/download/v0.1.1/rnp-0.1.1.tgz
sha256sum rnp-0.1.1.tgz 
```
c41346e9d63558750f5de380ef165561e07564c1672b4bbab4e43427ab61f019  rnp-0.1.1.tgz
```

**Comment by ronaldtse** [comment]
Submission successful!

<img width="834" alt="Screen Shot 2022-10-25 at 6 40 36 PM" src="https://user-images.githubusercontent.com/11865/197752695-ca07af51-78b5-4b65-8fd3-02274f1c4a21.png">

<img width="1158" alt="Screen Shot 2022-10-25 at 6 40 42 PM" src="https://user-images.githubusercontent.com/11865/197752671-ab6470d6-dfc9-4ea6-90cf-a14b3b6e4217.png">

Closing. Thank you @antonsviridenko !

**Comment by antonsviridenko** [comment]
https://pecl.php.net/package/rnp

**Comment by antonsviridenko** [comment]
https://www.php.net/manual/en/book.rnp.php
