### ISSUE TITLE
Bump php-rnp version after improvements from Remi Collet

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/php-rnp#7]
@antonsviridenko we need to bump the php-rnp version after improvements received from Remi:

* #4 
* #5

**Comment by antonsviridenko** [comment]
@ronaldtse 
New release is uploaded
https://github.com/rnpgp/php-rnp/releases/download/v0.2.0/rnp-0.2.0.tgz
sha256sum rnp-0.2.0.tgz 
```
4946bbd2ac3ce6415d965369611fe800f90833cb1966eb53506ae936182dbfa4  rnp-0.2.0.tgz
```
You can now try to upload the package to PECL.

**Comment by ronaldtse** [comment]
Done, thank you! 

<img width="1151" alt="Screenshot 2023-04-05 at 8 25 15 AM" src="https://user-images.githubusercontent.com/11865/229943932-f6a6a020-2d6d-444c-a61d-c7fdd73fb8a6.png">
